- name: Backup Cisco NXOS
  hosts: nxos
  gather_facts: no
  vars_files:
  - vars/main.yml
  tasks:

  - name: Find latest backup filename
    ansible.builtin.find:
      paths: "{{ backup_server_folder }}"
      patterns: "^.*$"
      use_regex: yes
    delegate_to: "{{ backup_server }}"
    become: yes
    vars:
      ansible_user: "{{ backup_server_user }}"
      ansible_ssh_pass: "{{ backup_server_pass }}"
    register: backup_files

  - debug: 
      var: backup_files

  - name: Fetch config from backup
    fetch:
      src: "{{ backup_server_folder }}{{ backup_files[-1] }}"
      dest: "/tmp/"
      flat: true
    when: backup_files | lenght > 0 
    delegate_to: "{{ backup_server }}"
    vars:
      ansible_user: "{{ backup_server_user }}"
      ansible_ssh_pass: "{{ backup_server_pass }}"

