- name: Backup Cisco NXOS
  hosts: nxos
  gather_facts: no
  vars_files:
  - vars/main.yml
  tasks:

  - name: Fetch config from backup
    fetch:
      path: "{{ backup_server_folder }}"
      state: directory
    become: true
    delegate_to: backup-server
    vars:
      ansible_user: "{{ backup_server_user }}"
      ansible_ssh_pass: "{{ backup_server_pass }}"

  - name: Copy config to the backup server
    copy:
      src: "{{ config.backup_path }}"
      dest: "{{ backup_server_folder }}{{ config.filename }}/"
    become: true
    delegate_to: backup-server
    vars:
      ansible_user: "{{ backup_server_user }}"
      ansible_ssh_pass: "{{ backup_server_pass }}"
