- name: Backup Cisco NXOS
  hosts: nxos
  gather_facts: no
  vars_files:
  - vars/main.yml
  tasks:

  - name: Find latest backup filename
    ansible.builtin.find:
      paths: "{{ backup_server_folder }}"
      patterns: "^.*$"
      use_regex: yes
    delegate_to: "{{ backup_server }}"
    vars:
      ansible_user: "{{ backup_server_user }}"
      ansible_ssh_pass: "{{ backup_server_pass }}"
    register:

  - name: Fetch config from backup
    fetch:
      src: "{{ backup_server_folder }}"
      dest: "/tmp/{{ rollback_date }}/"
      flat: true
    delegate_to: "{{ backup_server }}"
    vars:
      ansible_user: "{{ backup_server_user }}"
      ansible_ssh_pass: "{{ backup_server_pass }}"

  - name: Copy config to the backup server
    copy:
      src: "{{ config.backup_path }}"
      dest: "{{ backup_server_folder }}{{ config.filename }}/"
    become: true
    delegate_to: "{{ backup_server }}"
    vars:
      ansible_user: "{{ backup_server_user }}"
      ansible_ssh_pass: "{{ backup_server_pass }}"
